// EVEN FIBONACCI NUMBERS

// Problem 2

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1,2,3,5,8,13,21,34,55,89,...

// notice that start from 1,2,3,5 ... and not start from 0,1,1,2,3,5 so keep in mind that

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

// 4_000_000

const evenFibs = (n, current = 1, space = 1) => {
  if (current > n) return 0;

  if (!(current % 2)) {
    return current + evenFibs(n, current + space, current);
  }
  return evenFibs(n, current + space, current);
};

console.log(evenFibs(21)); // 2,8 = 10
console.log(evenFibs(4_000_000)); // 4613732
